version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "marcantoineg"
    reviewers:
      - "marcantoineg"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    assignees:
      - "marcantoineg"
    reviewers:
      - "marcantoineg"
    schedule:
      interval: "weekly"
